version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: securetickets
      DB_USER: postgres
      DB_PASS: postgres
    volumes:
      - ./sessions:/var/lib/php/sessions

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: securetickets
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:

