name: Deploy para EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v3

      - name: Criar chave SSH temporária
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > deploy_key
          chmod 600 deploy_key

      - name: Deploy via rsync
        run: |
          rsync -avz -e "ssh -i deploy_key -o StrictHostKeyChecking=no" ./ ec2-user@${{ secrets.EC2_HOST }}:/var/www/html/securetickets/

